reward_functions:
  - _target_: src.reward_function.diagnosis_reward.DiagnosisReward
    correct_reward: 1.0
    incorrect_reward: 0.0
    undiagnosed_reward: 0.0
  - _target_: src.reward_function.format_reward.FormatReward
    invalid_reward: 0.0
    valid_reward: 1.0

conf_cal_reward_func:
  _target_: src.reward_function.conf_cal_reward.ConfidenceCalibrationReward
  oof_reward: -1.0
  reward_scale: 1.0
  correctness_bonus: 0.0